#!/bin/bash

if [{UID} -ne 0 ]
then 
echo "you are not root youser"
exit 1
fi

## check the number of processors
C=`nproc`
	if [ S{C} -eq 1 ]
then 
	echo "This server is very small"
exit 2
fi

## checking memory

free -m
